workers_dev = true
name = "my-worker"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "test-db-202501"
database_id = "58e2d047-3151-4e2f-9b25-a035c00c6296"
migrations_dir = "drizzle"
